### PR TITLE
Support image digests in FROM instructions

### PR DESCRIPTION
**Pull request by thundergolfer**
This is a re-up of https://github.com/HewlettPackard/dockerfile-parser-rs/pull/15, but updates the test code to be compatible with current APIs and also includes some additional validation of the digest part (with tests).

### CODE REVIEW

**Comment by thundergolfer** [comment]
Sorry my IDE introduced a some indenting changes here, which artificially blows up the diff. I'll make sure to remove those before merge.

**Comment by zubieta** [comment]
It'll be pretty useful to have this PR or #15 merged to unblock https://github.com/dprint/dprint-plugin-dockerfile/issues/9.

**Comment by jayvdb** [comment]
ping @jonmcquillan

**Comment by jonmcquillan** [comment]
Sorry it took so long to get to looking at this.  Can you bump this with a nop to kick off the github actions I migrated the repo to?  @jayvdb

**Comment by thundergolfer** [comment]
@jayvdb done

**Review by jonmcquillan — APPROVED** [review]

**Pull request merged**
